version: '3'

services:
  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  metrics-db:
    image: postgres:14-alpine
    ports:
      - "8083:5432"
    environment:
      - POSTGRES_DB=kafkademo
      - POSTGRES_USER=kafkademo
      - POSTGRES_PASSWORD=kafkademo

  producer-service:
    build: ./producer
    ports:
      - "8081:8081"
    depends_on:
      - kafka
    environment:
      - KAFKA_URL=kafka:9092

  consumer-service:
    build: ./consumer
    ports:
      - "8082:8082"
    depends_on:
      - kafka
      - metrics-db
    environment:
      - DATABASE_URL=jdbc:postgresql://metrics-db:5432/kafkademo
      - DATABASE_USERNAME=kafkademo
      - DATABASE_PASSWORD=kafkademo
      - KAFKA_URL=kafka:9092