server:
  port: 8081

spring:
  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    bootstrap-servers: ${KAFKA_URL:localhost:9092}

management:
  endpoints:
    web:
      exposure:
        include: health, metrics